version: '3'
services:
  postgres:
    image: postgres:13
    container_name: sequelize-container
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - ${DB_PORT:-5432}:5432
    